const glossaryDgt = [
    { term: "Ángulo muerto o punto ciego", definition: "Zona de los laterales del coche que no es posible ver con los retrovisores.", image: "assets/glossary/angulo-muerto-o-punto-ciego.jpg" },
    { term: "Aparcamiento en batería", definition: "Colocar el coche mirando a la acera de tal manera que la parte de atrás o la parte de delante quedan mirando hacia la acera.", image: "assets/glossary/aparcamiento-en-bateria.jpg" },
    { term: "Apartadero", definition: "Parte más ancha que hay a veces en la carretera que sirve para que los vehículos paren cuando lo necesitan sin molestar a los demás conductores. Pero no es el arcén.", image: "assets/glossary/apartadero.jpg" },
    { term: "Arcén", definition: "Parte de la carretera que está a los lados de la calzada y por donde no circulan vehículos, excepto en casos especiales.", image: "assets/glossary/arcen.jpg" },
    { term: "Arcén peatonal", definition: "Parte de la carretera que está a los lados de la calzada por donde pueden caminar los peatones.", image: "assets/glossary/arcen-peatonal.jpg" },
    { term: "Autopista de peaje", definition: "Carretera con muchos carriles que hay que pagar para usarla .", image: "assets/glossary/autopista-de-peaje.jpg" },
    { term: "Badén", definition: "Zona de la carretera que se hunde. A veces se confunde con resalte, pero el resalte sube y el badén baja.", image: "assets/glossary/baden.jpg" },
    { term: "Balizamiento", definition: "Grupo de luces, señales o dispositivos que están en las obras para avisar la dirección que debes seguir.", image: "assets/glossary/balizamiento.jpg" },
    { term: "Bandas sonoras en el suelo", definition: "Líneas blancas que están en los bordes de la calzada que sirven para avisar al conductor con sonido y vibración y evitan que se salga de la carretera.", image: "assets/glossary/bandas-sonoras-en-el-suelo.jpg" },
    { term: "Calle residencial", definition: "Calle donde tienen preferencia los peatones sobre los vehículos.", image: "assets/glossary/calle-residencial.jpg" },
    { term: "Calzada", definition: "Parte de la calle o de la carretera por donde circulan los vehículos.", image: "assets/glossary/calzada.jpg" },
    { term: "Cambio de dirección", definition: "Giro a la derecha o a la izquierda.", image: "assets/glossary/cambio-de-direccion.jpg" },
    { term: "Cambio de rasante", definition: "Zona de la carretera que tiene poca visibilidad porque se encuentran 2 tramos con una inclinación diferente.", image: "assets/glossary/cambio-de-rasante.jpg" },
    { term: "Cambio de sentido", definition: "Circular al contrario de cómo ibas antes.", image: "assets/glossary/cambio-de-sentido.jpg" },
    { term: "Campo visual", definition: "Espacio que puedes ver al mismo tiempo sin mover los ojos.", image: "assets/glossary/campo-visual.jpg" },
    { term: "Cañada", definition: "Camino que se utiliza para que los pastores lleven al rebaño de un lugar a otro. También se llama cañada real, vía pecuaria y paso de ganado.", image: "assets/glossary/canada.jpg" },
    { term: "Captafaros horizontales", definition: "Señales de la vía que refejan la luz y sirven para indicar el sentido de la circulación y el límite de la calzada.", image: "assets/glossary/captafaros-horizontales.jpg" },
    { term: "Carretera 2+1", definition: "Carretera con 3 carriles y el carril central es para adelantar unas veces para un sentido y otras para el otro sentido.", image: "assets/glossary/carretera-2-1.jpg" },
    { term: "Carretera convencional", definition: "Carretera que no pasa por dentro de un poblado y que no es una autopista ni una autovía.", image: "assets/glossary/carretera-convencional.jpg" },
    { term: "Carretera multicarril", definition: "Carretera que tiene por lo menos 2 carriles de circulación en cada sentido y puede tener entradas y cruces. Cada sentido tiene una separación. Pero no son ni autopistas ni autovías", image: "assets/glossary/carretera-multicarril.jpg" },
    { term: "Carril de aceleración", definition: "Carril corto que te permite acelerar cuando vienes de una carretera y te incorporas a otra.", image: "assets/glossary/carril-de-aceleracion.jpg" },
    { term: "Carril de alta ocupación o VAO", definition: "Carril reservado para los vehículos con 2 o más pasajeros cuando hay mucho tráfco.", image: "assets/glossary/carril-de-alta-ocupacion-o-vao.jpg" },
    { term: "Carril de deceleración", definition: "Carril corto que te permite reducir la velocidad o desacelerar la marcha del vehículo cuando dejas una carretera.", image: "assets/glossary/carril-de-deceleracion.jpg" },
    { term: "Carril reversible", definition: "Carril central que puede servir para los 2 sentidos de la circulación dependiendo de la cantidad de tráfco. El sentido de la circulación de ese carril se indica con semáforos o con otras señales.", image: "assets/glossary/carril-reversible.jpg" },
    { term: "Cruce de vías", definition: "Lugar donde se encuentran 2 o más carreteras, caminos o calles.", image: "assets/glossary/cruce-de-vias.jpg" },
    { term: "Distancia de detención", definition: "Espacio que recorres desde que ves un obstáculo hasta que paras por completo. Por ejemplo, el tiempo que pasa desde que ves un semáforo en rojo hasta que paras.", image: "assets/glossary/distancia-de-detencion.jpg" },
    { term: "Distancia de frenado", definition: "Espacio que recorre el vehículo desde que empieza a frenar el conductor hasta que se para el vehículo por completo.", image: "assets/glossary/distancia-de-frenado.jpg" },
    { term: "Distancia de reacción", definition: "Espacio que recorre el vehículo desde que el conductor ve un peligro hasta que pisa el freno o gira el volante. Es el tiempo que tarda el conductor en reaccionar.", image: "assets/glossary/distancia-de-reaccion.jpg" },
    { term: "Distancia de seguridad", definition: "Distancia de separación entre 2 vehículos para evitar el peligro de choque por detrás.", image: "assets/glossary/distancia-de-seguridad.jpg" },
    { term: "Distancia de separación lateral", definition: "Distancia de separación en paralelo entre 2 vehículos al adelantar.", image: "assets/glossary/distancia-de-separacion-lateral.jpg" },
    { term: "Efecto de visión túnel", definition: "Efecto que ocurre cuando conduces a mucha velocidad. Con este efecto tienes menos capacidad de ver lo que pasa a los lados. Y solo ves lo que hay enfrente de ti, como si pasaras por un túnel.", image: "assets/glossary/efecto-de-vision-tunel.jpg" },
    { term: "Estrechamiento", definition: "Zona más estrecha de la carretera. A veces no pueden pasar 2 vehículos a la vez.", image: "assets/glossary/estrechamiento.jpg" },
    { term: "Glorieta", definition: "Tipo de cruce circular donde se unen varias carreteras o caminos. Siempre te diriges hacia la derecha cuando entras a una glorieta. También se llama rotonda.", image: "assets/glossary/glorieta.jpg" },
    { term: "Hitos de vértice", definition: "Señal con forma redondeada con 2 fechas que indican las 2 direcciones a seguir.", image: "assets/glossary/hitos-de-vertice.jpg" },
    { term: "Incorporarse", definition: "Unirse a otra carretera o empezar a circular cuando estás parado o aparcado.", image: "assets/glossary/incorporarse.jpg" },
    { term: "Inmovilizar un vehículo", definition: "Impedir que un vehículo se mueva porque ha incumplido una norma. Por ejemplo, un agente inmoviliza un vehículo cuando su conductor ha dado positivo en la prueba de alcoholemia.", image: "assets/glossary/inmovilizar-un-vehiculo.jpg" },
    { term: "Intersección", definition: "Cruce de varias carreteras o caminos.", image: "assets/glossary/interseccion.jpg" },
    { term: "Isleta", definition: "Zona de una vía o carretera que no se debe pisar con el vehículo.", image: "assets/glossary/isleta.jpg" },
    { term: "Linea contínua", definition: "Línea sin separaciones.", image: "assets/glossary/linea-continua.jpg" },
    { term: "Línea de detención", definition: "Línea pintada en el suelo en la que debes parar para cumplir una señal de tráfco.", image: "assets/glossary/linea-de-detencion.jpg" },
    { term: "Linea discontinua", definition: "Línea con separaciones.", image: "assets/glossary/linea-discontinua.jpg" },
    { term: "Marcas viales", definition: "Líneas o signos que están pintados sobre la calzada para informar, advertir o guiar a los vehículos.", image: "assets/glossary/marcas-viales.jpg" },
    { term: "Mediana", definition: "Zona que está en medio de la carretera que separa los 2 sentidos del tráfco y por la que no se puede circular.", image: "assets/glossary/mediana.jpg" },
    { term: "Parte transitable del arcén", definition: "Parte del arcén por donde pueden circular las personas y algunos vehículos. Por ejemplo: las bicicletas y los vehículos llevados por animales.", image: "assets/glossary/parte-transitable-del-arcen.jpg" },
    { term: "Paso a nivel", definition: "Cruce de una carretera con las vías por donde pasan el tren. Puede estar protegido por barreras o semibarreras.", image: "assets/glossary/paso-a-nivel.jpg" },
    { term: "Paso de ganado o vía pecuaria", definition: "Camino para que los pastores lleven al rebaño de un lugar a otro. También se llama cañada y cañada real.", image: "assets/glossary/paso-de-ganado-o-via-pecuaria.jpg" },
    { term: "Paso inferior", definition: "Túnel o paso subterráneo.", image: "assets/glossary/paso-inferior.jpg" },
    { term: "Paso rebajado", definition: "Rampa pequeña que une la acera con la calzada para facilitar el paso a las personas con movilidad reducida.", image: "assets/glossary/paso-rebajado.jpg" },
    { term: "Plataforma única", definition: "Calle o vía donde las aceras están al mismo nivel que la calzada.", image: "assets/glossary/plataforma-unica.jpg" },
    { term: "Poblado", definition: "Población, ciudad o pueblo.", image: "assets/glossary/poblado.jpg" },
    { term: "Prioridad de paso", definition: "Preferencia para pasar que tiene un vehículo o una persona sobre los demás.", image: "assets/glossary/prioridad-de-paso.jpg" },
    { term: "Puente móvil", definition: "Puente que se mueve o se levanta para dejar pasar a los barcos.", image: "assets/glossary/puente-movil.jpg" },
    { term: "Raqueta", definition: "Desvío en forma de medio círculo pintado con rayas que sirve para cambiar de dirección o de sentido en la carretera.", image: "assets/glossary/raqueta.jpg" },
    { term: "Refugio", definition: "Zona peatonal que está en la calzada por la que no pueden pasar los vehículos. Por ejemplo, la zona para parar entre 2 pasos de peatones.", image: "assets/glossary/refugio.jpg" },
    { term: "Resalte", definition: "Zona del suelo que se eleva un poco. Se puede confundir el resalte con el badén, pero el resalte se eleva y el badén se hunde.", image: "assets/glossary/resalte.jpg" },
    { term: "Semáforo de carril", definition: "Semáforo colocado encima de los carriles de la calzada.", image: "assets/glossary/semaforo-de-carril.jpg" },
    { term: "Señal V-20", definition: "Placa que indica que la carga del vehículo sobresale por detrás.", image: "assets/glossary/senal-v-20.jpg" },
    { term: "Señal horizontal", definition: "Señal o marca de tráfco pintada en el suelo.", image: "assets/glossary/senal-horizontal.jpg" },
    { term: "Señal vertical", definition: "Señal de tráfco que está de pie, a un lado de la vía.", image: "assets/glossary/senal-vertical.jpg" },
    { term: "Señales circunstanciales y de balizamiento", definition: "Luces, señales o aparatos para avisar las obras en una vía. Indican la dirección que debes seguir y avisan de los obstáculos que puedes encontrar.", image: "assets/glossary/senales-circunstanciales-y-de-balizamiento.jpg" },
    { term: "Tramo", definition: "Parte de un camino o vía.", image: "assets/glossary/tramo.jpg" },
    { term: "Travesía", definition: "Parte de la carretera que pasa por dentro de un poblado.", image: "assets/glossary/travesia.jpg" },
    { term: "Vado", definition: "Salida de un garaje por la acera que tiene una señal que prohíbe aparcar.", image: "assets/glossary/vado.jpg" },
    { term: "Vía", definition: "Camino por el que circulas. Por ejemplo: una carretera, una calle o una autopista.", image: "assets/glossary/via.jpg" },
    { term: "Vía de doble sentido", definition: "Vía con dos carriles, uno para un sentido de la circulación y otro carril para el sentido contrario.", image: "assets/glossary/via-de-doble-sentido.jpg" },
    { term: "Vía de sentido único", definition: "Vía por donde los vehículos deben circular solo en un sentido y está prohibida la circulación en sentido contrario.", image: "assets/glossary/via-de-sentido-unico.jpg" },
    { term: "Vía interurbana", definition: "Vía que pasa por fuera de un poblado.", image: "assets/glossary/via-interurbana.jpg" },
    { term: "Vía pavimentada", definition: "Vía cubierta por asfalto, que es un material negro y duro que se pone muchas veces en las calles y carreteras. Lo contrario es un camino de tierra.", image: "assets/glossary/via-pavimentada.jpg" },
    { term: "Vía pecuaria", definition: "Camino que se utiliza para que los pastores lleven al rebaño de un lugar a otro. También se llama paso de ganado, cañada y cañada real.", image: "assets/glossary/via-pecuaria.jpg" },
    { term: "Vía pública", definition: "Vía o espacio por donde pueden circular las personas y los vehículos, y no es privada porque ninguna persona es dueña de esa vía.", image: "assets/glossary/via-publica.jpg" },
    { term: "Vía urbana", definition: "Vía que pasa por dentro de una ciudad, un pueblo o un poblado.", image: "assets/glossary/via-urbana.jpg" },
    { term: "Visibilidad", definition: "Distancia que te permite ver a los otros vehículos, los objetos y la carretera.", image: "assets/glossary/visibilidad.jpg" },
    { term: "Zona balizada", definition: "Zona donde hay señales que avisan de un peligro o que no se puede pasar.", image: "assets/glossary/zona-balizada.jpg" },
    { term: "Zona de Bajas Emisiones o ZBE", definition: "Zona de la ciudad donde solo pueden entrar los vehículos que no dañan el medioambiente.", image: "assets/glossary/zona-de-bajas-emisiones-o-zbe.jpg" },
    { term: "Zona de cebreado", definition: "Zona cerrada por una línea que contiene rayas blancas. Esta zona no se puede pisar por los vehículos.", image: "assets/glossary/zona-de-cebreado.jpg" },
    { term: "Zona de coexistencia", definition: "Vía compartida para peatones, vehículos y bicicletas donde el peatón tiene prioridad.", image: "assets/glossary/zona-de-coexistencia.jpg" },
    { term: "Zona de incertidumbre", definition: "Lugar de la vía donde no sabemos cómo reaccionan los vehículos.", image: "assets/glossary/zona-de-incertidumbre.jpg" },
    { term: "Zona urbana", definition: "Zona que está dentro de un poblado. Por ejemplo: en una ciudad o en un pueblo.", image: "assets/glossary/zona-urbana.jpg" }
];
